### PR TITLE
Peach algo optimisations and Introduction of Test Cases

### PR DESCRIPTION
**Pull request by chrisdigity**
This pull request introduces mining algorithm optimisations of about a 30% increase in haikurate per second. It also introduces a "Test Case" called `test_miner` originally designed by @krypdkat  to test the optimisations developed into the Peach algorithm. The "Test Case" was then further developed to allow convenient regression and efficiency testing of any mining algorithm optimisations, for proof of performance and efficiency as can be seen below.

Original Peach mining*
Screenshot from 2019-07-24 10-26-17

Optimised Peach mining*
Screenshot from 2019-07-24 10-26-28

*Tests were performed on an MX150 Nvidia Laptop GPU with 64 iterations of random difficulty 20 block solves, and actual haikurate performance gains may vary depending on card and system config.

### CODE REVIEW

**Comment by chrisdigity** [comment]
I'm waiting on multi-GPU Test Rigs to confirm and validate solves on main-net before releasing this pull request for merging. Please standby...

**Comment by krypdkat** [comment]
great work, LGTM :+1:

**Comment by chrisdigity** [comment]
These mining optimizations have now been validated on Mainnet, and will be made available for merge.

**Comment by chrisdigity** [comment]
As of 31229ea8cf73fbdc2a6be050f8d747e914f31e11, this pull request is redundant and will be closed without merge.

**Pull request closed without merging**
