### PR TITLE
V2 trigger height

### PR DESCRIPTION
**Pull request by 0rtis**
Use global variable for V2 trigger.
Edit comment of reward calculation function to correct trigger height

### CODE REVIEW

**Comment by pzmarzly** [comment]
Git is hard.

```bash
git checkout v2-trigger-height
git rebase -i origin/master
```

Then remove unnecessary commits.

```bash
git push -f
```

**Comment by 0rtis** [comment]
What is the point of `rebase` here ?

**Comment by pzmarzly** [comment]
Sorry, I meant `git rebase -i HEAD~5`.

This opens this TUI (I'm using env. var. `EDITOR=nano`):

screenshot from 2018-11-02 18-12-40

There you can reorder commits, merge them, edit commit message, or delete commits altogether (just remove the relevant line).

Then `git push -f` pushes your changes (without `-f`/`--force` it only uploads when you add, not change the past).

**Comment by pzmarzly** [comment]
The reason behind keeping only the relevant commits in PR is that repository owner may want to merge only one of your PRs, not all of them.

**Pull request merged**
