### PR TITLE
MakeFile for easier debugging

### PR DESCRIPTION
**Pull request by 0rtis**
Creating a standard MakeFile to smooth IDE debugging

### CODE REVIEW

**Comment by pzmarzly** [comment]
I don't think compilation time is an issue, so a Makefile could look simply like this:

```makefile
all:
	./makeunx bin
	./makeunx install
debug:
	./makeunx bin -g
	./makeunx install
clean:
	./makeunx clean
```

No code duplication then.

And for IDE-specific gitignore: https://davidwalsh.name/global-gitignore

**Comment by 0rtis** [comment]
MakeFile is a standard format. Easier for community to play with I believe.

**Comment by pzmarzly** [comment]
Bash scripts are also pretty standardized, and more flexible (or at least there are more Bash wizards than Makefile ones). `makeunx` could use some refactoring, though, I agree.

**Comment by pzmarzly** [comment]
screenshot from 2018-11-02 15-36-31

Please use different branch. To move commit to other branch:

```bash
git branch new-branch
git reset --hard origin/master
git checkout new-branch
```

**Comment by 0rtis** [comment]
That did not work. I will create a branch next time for sure.

**Comment by 0rtis** [comment]
All change are packed in https://github.com/mochimodev/mochimo/pull/14

**Pull request closed without merging**
